//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketPermiumServiceRef
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginResponse", Namespace="http://schemas.datacontract.org/2004/07/TicketPremium.Controlador.DTOs")]
    public partial class LoginResponse : object
    {
        
        private bool ExitoField;
        
        private string MensajeField;
        
        private int UsuarioIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Exito
        {
            get
            {
                return this.ExitoField;
            }
            set
            {
                this.ExitoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UsuarioId
        {
            get
            {
                return this.UsuarioIdField;
            }
            set
            {
                this.UsuarioIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PartidoDTO", Namespace="http://schemas.datacontract.org/2004/07/FederacionFutbol.Servicio.DTOs")]
    public partial class PartidoDTO : object
    {
        
        private int CodigoField;
        
        private string EquipoLocalField;
        
        private string EquipoVisitaField;
        
        private System.DateTime FechaField;
        
        private string LugarField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EquipoLocal
        {
            get
            {
                return this.EquipoLocalField;
            }
            set
            {
                this.EquipoLocalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EquipoVisita
        {
            get
            {
                return this.EquipoVisitaField;
            }
            set
            {
                this.EquipoVisitaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha
        {
            get
            {
                return this.FechaField;
            }
            set
            {
                this.FechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lugar
        {
            get
            {
                return this.LugarField;
            }
            set
            {
                this.LugarField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LocalidadDTO", Namespace="http://schemas.datacontract.org/2004/07/FederacionFutbol.Servicio.DTOs")]
    public partial class LocalidadDTO : object
    {
        
        private string CodigoLocalidadField;
        
        private int DisponibilidadField;
        
        private decimal PrecioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoLocalidad
        {
            get
            {
                return this.CodigoLocalidadField;
            }
            set
            {
                this.CodigoLocalidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Disponibilidad
        {
            get
            {
                return this.DisponibilidadField;
            }
            set
            {
                this.DisponibilidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Precio
        {
            get
            {
                return this.PrecioField;
            }
            set
            {
                this.PrecioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompraRequest", Namespace="http://schemas.datacontract.org/2004/07/TicketPremium.Controlador.DTOs")]
    public partial class CompraRequest : object
    {
        
        private int CantidadField;
        
        private string CodigoLocalidadField;
        
        private int CodigoPartidoField;
        
        private System.DateTime FechaPartidoField;
        
        private string PartidoDescripcionField;
        
        private decimal PrecioUnitarioField;
        
        private int UsuarioIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad
        {
            get
            {
                return this.CantidadField;
            }
            set
            {
                this.CantidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoLocalidad
        {
            get
            {
                return this.CodigoLocalidadField;
            }
            set
            {
                this.CodigoLocalidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoPartido
        {
            get
            {
                return this.CodigoPartidoField;
            }
            set
            {
                this.CodigoPartidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaPartido
        {
            get
            {
                return this.FechaPartidoField;
            }
            set
            {
                this.FechaPartidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartidoDescripcion
        {
            get
            {
                return this.PartidoDescripcionField;
            }
            set
            {
                this.PartidoDescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PrecioUnitario
        {
            get
            {
                return this.PrecioUnitarioField;
            }
            set
            {
                this.PrecioUnitarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UsuarioId
        {
            get
            {
                return this.UsuarioIdField;
            }
            set
            {
                this.UsuarioIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompraResponse", Namespace="http://schemas.datacontract.org/2004/07/TicketPremium.Controlador.DTOs")]
    public partial class CompraResponse : object
    {
        
        private bool ExitoField;
        
        private int FacturaIdField;
        
        private decimal IvaField;
        
        private string MensajeField;
        
        private decimal SubtotalField;
        
        private decimal TotalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Exito
        {
            get
            {
                return this.ExitoField;
            }
            set
            {
                this.ExitoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FacturaId
        {
            get
            {
                return this.FacturaIdField;
            }
            set
            {
                this.FacturaIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Iva
        {
            get
            {
                return this.IvaField;
            }
            set
            {
                this.IvaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Subtotal
        {
            get
            {
                return this.SubtotalField;
            }
            set
            {
                this.SubtotalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Total
        {
            get
            {
                return this.TotalField;
            }
            set
            {
                this.TotalField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResumenVentaDTO", Namespace="http://schemas.datacontract.org/2004/07/TicketPremium.Controlador.DTOs")]
    public partial class ResumenVentaDTO : object
    {
        
        private TicketPermiumServiceRef.ResumenVentaDetalleDTO[] DetallesField;
        
        private System.DateTime FechaField;
        
        private string PartidoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TicketPermiumServiceRef.ResumenVentaDetalleDTO[] Detalles
        {
            get
            {
                return this.DetallesField;
            }
            set
            {
                this.DetallesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha
        {
            get
            {
                return this.FechaField;
            }
            set
            {
                this.FechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Partido
        {
            get
            {
                return this.PartidoField;
            }
            set
            {
                this.PartidoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResumenVentaDetalleDTO", Namespace="http://schemas.datacontract.org/2004/07/TicketPremium.Controlador.DTOs")]
    public partial class ResumenVentaDetalleDTO : object
    {
        
        private string LocalidadField;
        
        private decimal TotalRecaudadoField;
        
        private int VendidosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Localidad
        {
            get
            {
                return this.LocalidadField;
            }
            set
            {
                this.LocalidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalRecaudado
        {
            get
            {
                return this.TotalRecaudadoField;
            }
            set
            {
                this.TotalRecaudadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Vendidos
        {
            get
            {
                return this.VendidosField;
            }
            set
            {
                this.VendidosField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TicketPermiumServiceRef.ITicketPremiumService")]
    public interface ITicketPremiumService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITicketPremiumService/Login", ReplyAction="http://tempuri.org/ITicketPremiumService/LoginResponse")]
        System.Threading.Tasks.Task<TicketPermiumServiceRef.LoginResponse> LoginAsync(string nombreUsuario, string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITicketPremiumService/ObtenerPartidosDisponibles", ReplyAction="http://tempuri.org/ITicketPremiumService/ObtenerPartidosDisponiblesResponse")]
        System.Threading.Tasks.Task<TicketPermiumServiceRef.PartidoDTO[]> ObtenerPartidosDisponiblesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITicketPremiumService/ObtenerLocalidadesPorPartido", ReplyAction="http://tempuri.org/ITicketPremiumService/ObtenerLocalidadesPorPartidoResponse")]
        System.Threading.Tasks.Task<TicketPermiumServiceRef.LocalidadDTO[]> ObtenerLocalidadesPorPartidoAsync(int codigoPartido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITicketPremiumService/ComprarBoletos", ReplyAction="http://tempuri.org/ITicketPremiumService/ComprarBoletosResponse")]
        System.Threading.Tasks.Task<TicketPermiumServiceRef.CompraResponse> ComprarBoletosAsync(TicketPermiumServiceRef.CompraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITicketPremiumService/ObtenerResumenVentas", ReplyAction="http://tempuri.org/ITicketPremiumService/ObtenerResumenVentasResponse")]
        System.Threading.Tasks.Task<TicketPermiumServiceRef.ResumenVentaDTO> ObtenerResumenVentasAsync(int codigoPartido);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ITicketPremiumServiceChannel : TicketPermiumServiceRef.ITicketPremiumService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class TicketPremiumServiceClient : System.ServiceModel.ClientBase<TicketPermiumServiceRef.ITicketPremiumService>, TicketPermiumServiceRef.ITicketPremiumService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TicketPremiumServiceClient() : 
                base(TicketPremiumServiceClient.GetDefaultBinding(), TicketPremiumServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ITicketPremiumService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TicketPremiumServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(TicketPremiumServiceClient.GetBindingForEndpoint(endpointConfiguration), TicketPremiumServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TicketPremiumServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TicketPremiumServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TicketPremiumServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TicketPremiumServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TicketPremiumServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<TicketPermiumServiceRef.LoginResponse> LoginAsync(string nombreUsuario, string clave)
        {
            return base.Channel.LoginAsync(nombreUsuario, clave);
        }
        
        public System.Threading.Tasks.Task<TicketPermiumServiceRef.PartidoDTO[]> ObtenerPartidosDisponiblesAsync()
        {
            return base.Channel.ObtenerPartidosDisponiblesAsync();
        }
        
        public System.Threading.Tasks.Task<TicketPermiumServiceRef.LocalidadDTO[]> ObtenerLocalidadesPorPartidoAsync(int codigoPartido)
        {
            return base.Channel.ObtenerLocalidadesPorPartidoAsync(codigoPartido);
        }
        
        public System.Threading.Tasks.Task<TicketPermiumServiceRef.CompraResponse> ComprarBoletosAsync(TicketPermiumServiceRef.CompraRequest request)
        {
            return base.Channel.ComprarBoletosAsync(request);
        }
        
        public System.Threading.Tasks.Task<TicketPermiumServiceRef.ResumenVentaDTO> ObtenerResumenVentasAsync(int codigoPartido)
        {
            return base.Channel.ObtenerResumenVentasAsync(codigoPartido);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ITicketPremiumService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ITicketPremiumService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:64188/Controlador/Servicios/TicketPremiumService.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return TicketPremiumServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ITicketPremiumService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return TicketPremiumServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ITicketPremiumService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ITicketPremiumService,
        }
    }
}
